config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  root "welcome#index"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings
    resources :reservations
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/listings" => "listings#all"
  post "/verify/:id" => "listings#verify", as: "verify"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  post "/listings/:id/delete_photos/:photo_id" => "listings#destroy_image", as: "delete_photos"

  post "braintree/checkout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
   self.new(
     provider: auth_hash["provider"],
     uid: auth_hash["uid"],
     token: auth_hash["credentials"]["token"]
     )
   end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :reservations
  mount_uploaders :photos, PhotoUploader

  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :listing
  mount_uploader :image, PhotoUploader
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :reservations

  enum role: [:customer, :moderator, :superadmin]

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      first_name: auth_hash["extra"]["raw_info"]["first_name"],
      last_name: auth_hash["extra"]["raw_info"]["last_name"],
      email: auth_hash["extra"]["raw_info"]["email"],
      password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end

  # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
     :amount => "10.00", #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )

    if result.success?
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def index
    # @listings = Listing.all
    @user = current_user
    @listings = Listing.order('created_at DESC').page(params[:page]).per(15)
  end

  def all
    # @listings = Listing.all
    @user = current_user
    @listings = Listing.order('created_at DESC').page(params[:page]).per(15)
  end

  def show
    @listing = Listing.find(params[:id])
    @user = current_user
    @reservation = Reservation.new
  end

  def verify
    @listing = Listing.find(params[:id])
    @user = current_user

    @listing.verified = true
    @listing.save
    redirect_to user_listing_path(@user, @listing)
  end

  def new
    @listing = Listing.new
    @user = current_user
  end

  def edit
    @listing = Listing.find(params[:id])
    # @listing.photos.build
  end

  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      redirect_to '/listings'
    else
      render template: "/listings/new"
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to '/listings'
    else
      render template: "/listings/edit"
    end
  end

  def destroy
    @listing.destroy
    redirect_to '/listings'
  end

  def destroy_image
    @listing = Listing.find(params[:id])

    remove_image_at_index(params[:photo_id].to_i)
    flash[:error] = "Failed at deleting image" unless @listing.save
    redirect_to '/listings'
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:user_id, :name, :place_type, :room_number, :bed_number, :guest_number, :country, :state, :city, :address, :price, :description, :verified, {photos: []}, photos_attributes: [
      :id,
      :image,
      :_destroy
      ])
  end

  def remove_image_at_index(index)
    byebug
    remain_images = @listing.photos # copy the array
    deleted_image = remain_images.delete_at(index) # delete the target image
    deleted_image.try(:remove!) # delete image from S3
    @listing.photos = remain_images # re-assign back
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :require_login

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new

  end

  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      ReservationMailer.booking_email(@reservation.user_id).deliver_later

      redirect_to user_reservations_path
    else
      render template: "/reservations/new"
    end

  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :listing_id, :start_date, :end_date, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def create_from_omniauth
     auth_hash = request.env["omniauth.auth"]
     authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

     # if: previously already logged in with OAuth
     if authentication.user
       user = authentication.user
       authentication.update_token(auth_hash)
       @next = root_url
       @notice = "Signed in!"
     # else: user logs in with OAuth for the first time
     else
       user = User.create_with_auth_and_hash(authentication, auth_hash)
       # you are expected to have a path that leads to a page for editing user details
       @next = users_edit_path
       @notice = "User created. Please confirm or edit details"
     end

     sign_in(user)
     redirect_to @next, :notice => @notice
   end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to '/listings'
    else
      render template: '/users/edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :gender, :phone, :country, :birthdate)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
  end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/braintree/new.html.slim
script[src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"]
script[src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"]

div.payment-header
  h3 Make Payment

.demo-frame data-token=@client_token
  = form_for :checkout_form, url: braintree_checkout_path ,html: { id: "cardForm" } do |form|
    = form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"}
    #card-number.hosted-field
    = form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"}
    #expiration-date.hosted-field
    = form.label :cvv, "CVV", html: {class: "hosted-fields--label"}
    #cvv.hosted-field
    = form.hidden_field "payment_method_nonce"
    .button-container
      = form.submit "Purchase", disabled: true, class: "button btn btn-primary", id: "submit-payment-btn"

javascript:
  var form = document.querySelector('#cardForm');
  var submit = document.querySelector("#submit-payment-btn");
  var authorization = $(".demo-frame").data("token");

  console.log("hello")

  braintree.client.create({
    // Replace this with your own authorization.
    authorization: authorization
  }, function (clientErr, clientInstance) {
    if (clientErr) {
    console.log(clientErr)
      // Handle error in client creation
      return;
    }

    braintree.hostedFields.create({
      client: clientInstance,
      styles: {
        'input': {
          'font-size': '14pt'
        },
        'input.invalid': {
          'color': 'red'
        },
        'input.valid': {
          'color': 'green'
        }
      },
      fields: {
        number: {
          selector: '#card-number',
          placeholder: '4111 1111 1111 1111'
        },
        cvv: {
          selector: '#cvv',
          placeholder: '123'
        },
        expirationDate: {
          selector: '#expiration-date',
          placeholder: '10/2019'
        }
      }
    }, function (hostedFieldsErr, hostedFieldsInstance) {
      if (hostedFieldsErr) {
        // Handle error in Hosted Fields creation
        return;
      }

      submit.removeAttribute('disabled');

      form.addEventListener('submit', function (event) {
        event.preventDefault();

        hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
          if (tokenizeErr) {
          console.log(tokenizeErr)
            // Handle error in Hosted Fields tokenization
            return;
          }

          // Put `payload.nonce` into the `payment_method_nonce` input, and then
          // submit the form. Alternatively, you could send the nonce to your server
          // with AJAX.
          document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
          form.submit();
        });
      }, false);
    });
  });

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PairBnB
    = javascript_include_tag 'application'
    = stylesheet_link_tag 'application'
    = csrf_meta_tag
  body
    #header
      = link_to "Home", root_path
      - if signed_in?
        = link_to "Profile", edit_user_path(current_user)
        = link_to "Reservations", user_reservations_path(current_user)
        = link_to "Listings", user_listings_path(current_user)
        = link_to t(".sign_out"), sign_out_path, method: :delete
      - else
        = link_to t(".sign_in"), sign_in_path
    #flash
      - flash.each do |key, value|
        |  <div id="flash_
        = key
        | ">
        =h value
    = yield

app/views/listings/_create.html.slim
div.header
  h1 Create Listing

div.create_form
  = form_for [current_user, @listing] do |f|
    div.field
      = f.label :name
      br
      = f.text_field :name
    div.field
      = f.label :description
      br
      = f.text_field :description
    div.field
      = f.label :place_type
      br
      = f.text_field :place_type
    div.field
      = f.label :room_number
      br
      = f.number_field :room_number
    div.field
      = f.label :bed_number
      br
      = f.number_field :bed_number
    div.field
      = f.label :guest_number
      br
      = f.number_field :guest_number
    div.field
      = f.label :country
      br
      = f.text_field :country
    div.field
      = f.label :state
      br
      = f.text_field :state
    div.field
      = f.label :city
      br
      = f.text_field :city
    div.field
      = f.label :address
      br
      = f.text_field :address
    div.field
      = f.label :price
      br
      = f.number_field :price
    div.field
      = f.label :photos
      = f.file_field :photos, multiple: true
    div.field
      = f.hidden_field :user_id, value: current_user.id
    div.actions
      = f.submit

app/views/listings/_edit.html.slim
div.edit_form
  = form_for [current_user, @listing] do |f|
    div.field
      = f.label :name
      br
      = f.text_field :name
    div.field
      = f.label :description
      br
      = f.text_field :description
    div.field
      = f.label :place_type
      br
      = f.text_field :place_type
    div.field
      = f.label :room_number
      br
      = f.number_field :room_number
    div.field
      = f.label :bed_number
      br
      = f.number_field :bed_number
    div.field
      = f.label :guest_number
      br
      = f.number_field :guest_number
    div.field
      = f.label :country
      br
      = f.text_field :country
    div.field
      = f.label :state
      br
      = f.text_field :state
    div.field
      = f.label :city
      br
      = f.text_field :city
    div.field
      = f.label :address
      br
      = f.text_field :address
    div.field
      = f.label :price
      br
      = f.number_field :price
    div.field
      = f.label :photos
      = f.file_field :photos, multiple: true
      br
    div.field
      - if @listing.photos != nil
        - @listing.photos.each_with_index do |image, index|
          = image_tag(image.url)
          br
          = link_to "Delete", delete_photos_path(@listing.id, index), method: :post
    div.field
      = f.hidden_field :user_id, value: current_user.id
    div.actions
      = f.submit

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/all.html.slim
p#notice
  = notice

div.listing-title
  h1 Listings

div.listing-container
  - @listings.each do |listing|
    div.listing-card
      div.listing-name
        = listing.name
      br
      div.listing-details
        = listing.country
        br
        = listing.city
      div.listing-links
        = link_to 'Show', user_listing_path(@user.id, listing.id), method: :get
        = link_to 'Edit', edit_user_listing_path(@user.id, listing.id), method: :get
        = link_to 'Destroy', user_listing_path(@user.id, listing.id), method: :delete, data: { confirm: 'Are you sure?' }

div.pagination
  = paginate @listings

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'edit', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/index.html.slim
p#notice
  = notice

div.listing-title
  h1 Listings

div.listing-container
  - @listings.each do |listing|
    div.listing-card
      div.listing-name
        = listing.name
      br
      div.listing-details
        = listing.country
        br
        = listing.city
      div.listing-links
        = link_to 'Show', user_listing_path(@user.id, listing.id), method: :get
        = link_to 'Edit', edit_user_listing_path(@user.id, listing.id), method: :get
        = link_to 'Destroy', user_listing_path(@user.id, listing.id), method: :delete, data: { confirm: 'Are you sure?' }

div.pagination
  = paginate @listings

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'create', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.slim
p#notice
  = notice

div.listing-top
  div.listing-header
    = @listing.name
  br
  div.listing-desc
    = @listing.description

div.images
  = form_for [current_user, @listing] do |f|
    = f.label :photos
    - if @listing.photos != nil
      - @listing.photos.each_with_index do |image, index|
        = image_tag(image.url)

div.listing-bottom
  div.listing-details
    h4 Place type
    = @listing.place_type
    h4 Number of rooms
    = @listing.room_number
    h4 Number of beds
    = @listing.bed_number
    h4 Number of guests
    = @listing.guest_number
    h4 Address
    = @listing.address
    br
    = @listing.city
    br
    = @listing.state
    br
    = @listing.country

  div.listing-price
    h3
      | Price Per Night
      br
      = @listing.price
      br
      | Verified Property:
      br
      = @listing.verified

    - if @user.moderator? || @user.superadmin?
      = button_to 'Verify Listing', verify_path(@listing)

  div.reserve
    = render partial: '/reservations/create'
    
h6
  = link_to 'Back', listings_path

app/views/reservations/_create.html.slim
div.create_form
  = form_for [@user, @reservation] do |f|
    div.field
      = f.label :start_date
      br
      = f.date_field :start_date
    div.field
      = f.label :end_date
      br
      = f.date_field :end_date
    div.field
      = f.hidden_field :user_id, value: current_user.id
    div.field
      = f.hidden_field :listing_id, value: @listing.id
    div.actions
      = f.submit

app/views/reservations/index.html.slim
div.reservation-title
  h1 My Reservations

div.payments
  = link_to "Make Payment", braintree_new_path

div.reservations-container
  - @reservations.each do |reservation|
    div.reservation-part
      h4
        = reservation.listing.name
      p
        | Booking from:
        br
        = reservation.start_date
      p
        | Until:
        br
        = reservation.end_date
      p
        | Cost per night:
        br
        = reservation.listing.price
      hr

app/views/reservations/new.html.slim
/ h1 New Reservation Page
/
/ div.create_form
/   = form_for [current_user, @reservations] do |f|
/     = f.hidden_field :listing_id, value: @listing.id
/     = f.hidden_field :user_id, value: current_user.id
/
/     = @listing.name
/     = f.label :start_date
/     = f.date_field :start_date
/
/     = f.label :end_date
/     = f.date_field :end_date
/
/     = f.submit

app/views/reservations/show.html.slim
h1 Show Reservation Page

div.reservations-container

app/views/users/_form.html.slim
.text-field
  = form.label :first_name
  br
  = form.text_field :first_name

.text-field
  = form.label :last_name
  br
  = form.text_field :last_name

.text-field
  = form.label :email
  br
  = form.text_field :email, type: 'email'

.password-field
  = form.label :password
  br
  = form.password_field :password

app/views/users/_newuser.html.slim
= form_for @user do |form|
  .text-field
    = form.label :first_name
    = form.text_field :first_name
  .text-field
    = form.label :last_name
    = form.text_field :last_name
  .text-field
    = form.label :email
    = form.text_field :email, type: 'email'
  .password-field
    = form.label :password
    = form.password_field :password
  .submit-field.btn.btn-success
    = form.submit

app/views/users/_profile.html.slim
div.edit_form
  = form_for @user do |f|
    br
    h4 User Account
    .text-field
      = f.label :first_name
      br
      = f.text_field :first_name
    br
    .text-field
      = f.label :last_name
      br
      = f.text_field :last_name
    br
    .text-field
      = f.label :email
      br
      = f.text_field :email, type: 'email'
    / .password-field
    /   = f.label :password
    /   = f.password_field :password
    br
    br
    h4 Biodata Information
    .text-field
      = f.label :gender
      br
      = f.text_field :gender
    br
    .text-field
      = f.label :phone
      br
      = f.text_field :phone
    br
    .text-field
      = f.label :country
      br
      = f.text_field :country
    br
    .text_field
      = f.label :birthdate
      br
      = f.date_field :birthdate
    br
    .submit-field
      = f.submit

app/views/users/edit.html.slim
div.title
  h1
    | Edit Profile

div.edit_profile
  div.profile
    = render partial: '/users/profile'

  div.links
    = link_to 'Your Listings', user_listings_path(current_user)
    br
    br
    = link_to 'Create New Listing', new_user_listing_path(current_user)
    br
    br
    = link_to 'Home', root_path

app/views/users/new.html.slim
#clearance.sign-up
  h2
    = t(".title")
  br
  = form_for @user do |form|
    = render partial: '/users/form', object: form
    .submit-field
      br
      = form.submit

app/views/welcome/index.html.slim
div.body-container
  div.hero-header
    h1.header-title
      | PairBnB
    h3
      | Find your next holiday home here.
    div.account
      - if signed_in?
        div.listings
          = link_to("/listings") do
            h4 All Listings
          end
      - else
        div.account-links
          = link_to "Sign up with email", sign_up_path
          br
          br
          = link_to "Sign in with email", sign_in_path
          br
        div.fb-login
          = link_to("/auth/facebook") do
            = image_tag 'https://rewards.meritushotels.com/img/420GNbXtI43K6/images/facebook-login-blue.png', class: 'fb_login'
            end